[build]
  # Build command
  command = "npm run build"

  # Directory to publish (build output)
  publish = "dist"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Environment variables for production
[context.production.environment]
  GEMINI_API_KEY = "your_gemini_api_key_here"
  VITE_SUPABASE_URL = "https://your-project-ref.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key_here"

# Development environment
[context.deploy-preview.environment]
  NPM_FLAGS = "--version"

# Production deployment settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co https://*.gemini.ai https://fonts.googleapis.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

# SPA Routing - React Router Support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes (if any)
[[redirects]]
  from = "/api/*"
  to = "https://your-api-domain.com/:splat"
  status = 200
